### ISSUE TITLE
Moving Weekly Sync to a Different Time/Day

### ISSUE THREAD

**Issue by lidel** [ipfs/in-web-browsers#106]
The GUI/WB team happens to be located in EU so we've been talking about meeting at an earlier time to give it more breathing room before All Hands Community call.

@hacdias proposed moving our weekly sync to 9 AM UTC on Monday and I think @fsdiogo suggested moving to 9:30 AM due to morning traffic.

Let's try new time next week and if it works.

Thoughts? :+1: / :-1:  ? Proposals of a different day? 
(Please use UTC timezone to avoid confusion)

**Comment by lidel** [comment]
I am okay with any time, but something to note is that  [9AM UTC is not very friendly for people from US](https://www.timeanddate.com/worldclock/converter.html?iso=20180910T090000&p1=224&p2=179&p3=1440&p4=133&p5=136&p6=262&p7=166&p8=176&p9=33&p10=240). So far the call had an internal character and participants were all from EU, but if that changes we should revisit.

**Comment by fsdiogo** [comment]
I like it being on a Monday, it makes it easier to think about we did last week without having to split between *sprints*.

About the time, I don't have a strong opinion. If I had to choose I would say **10AM UTC** as we're all in a very similar time zone (just one hour apart).

But **09:30AM UTC** works for me.

**Comment by alanshaw** [comment]
I'm fine with moving it to the morning. How much breathing room do you need though, why not just move it a half hour earlier so that it doesn't completely exclude the US?

**Comment by hacdias** [comment]
So, is it **9 AM UTC** // **10 AM UTC+1** (Lisbon, London) // **11 AM UTC+2** (Poland)?

**Comment by lidel** [comment]
We were able to do it today around **9:30 AM UTC**. 
Should  we make it official and update [IPFS Community](https://github.com/ipfs/community#calendar) calendar to reflect that?

**Comment by lidel** [comment]
Ok, let's keep this open until https://github.com/ipfs/pm/issues/555 is solved.

TODO:
- rename "Web Browser Working Group Weekly IRC Sync" to "Web Browser & GUI WG Weekly Sync"
- move it to 9:30 AM UTC

**Comment by lidel** [comment]
Comminuty calendar updated :+1:
