### ISSUE TITLE
Move Meeting Notes to ipfs/pm

### ISSUE THREAD

**Issue by lidel** [ipfs/in-web-browsers#130]
>   - Current location: [ipfs/in-web-browsers/meeting-notes](https://github.com/ipfs/in-web-browsers/tree/master/meeting-notes)
>   - Alternative location: [ipfs/pm/meeting-notes/](https://github.com/ipfs/pm/tree/master/meeting-notes/2018)
>     - Why? Better discovery, JS, Cluster and DDC WGs are there
> 

All other WGs moved to:
https://github.com/ipfs/pm/tree/master/meeting-notes/2018

During #127 we decided to do the same.

**Comment by autonome** [comment]
Hi Marcin, does this mean to watch new meeting notes, I should follow the
other repo instead of here?

**Comment by mikeal** [comment]
Having all the notes from different WG's in one repository makes it a lot harder for people to follow just the WG's they care about :(

**Comment by autonome** [comment]
I haven't checked out the other repo yet, so for my use-case, I'm not sure
it will be harder to follow along, or make it easier to find out about
other things happening. Which might be awesome learnings, or totally
distracting :)

**Comment by lidel** [comment]
@autonome @mikeal  No need to change your habits :) My plan is to  continue publishing issues for weekly sync in this repo (`ipfs/in-web-browsers`), they will include link to meeting notes, so there is no need to watch anything else. 

ps. I've been thinking about having a single issue instead of creating one-per-week – would that make things easier to follow (less noisy perhaps), or it is good as it is now (each week == separate issue)?

**Comment by autonome** [comment]
Either way, I need to click through to find the actual notes themselves, so
doesn't matter much to me :)

**Comment by lidel** [comment]
**_Final update:_**

To minimize notification noise in this repo (and in general) we've moved meeting updates to:

- GUI & In Web Browsers Weekly Sync @ https://github.com/ipfs/team-mgmt/issues/790

If you want to follow weekly meeting notes, subscribe to that one issue :)
