### ISSUE TITLE
ipfs-companion for Firefox removed?

### ISSUE THREAD

**Issue by Derrick-** [ipfs/in-web-browsers#141]
Anyone know what happened here?

https://addons.mozilla.org/firefox/addon/ipfs-companion/

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

**Comment by fsdiogo** [comment]
Check https://github.com/ipfs-shipyard/ipfs-companion/issues/679 for context and updates.

**Comment by lidel** [comment]
Resolved: https://github.com/ipfs-shipyard/ipfs-companion/issues/679#issuecomment-464074500 :tada:
