### ISSUE TITLE
Administrator Access Denied

### ISSUE THREAD

**Issue by mlock7232** [ipfs/in-web-browsers#149]
Im being blocked by a Administrator on Windows 10 Pro. My Passwords are not working , only sign-into lock page. How do I gain control back of my Laptop. Lenovo N23 8OUROO1FUS...HELP!!

**Comment by mlock7232** [comment]
Everything I try to access or change is being blocked by Administrator Security box asking me for my passwords that don't even work when entered in.

**Comment by lidel** [comment]
@mlock7232 this is issue tracker is about IPFS in Web Browsers, not Windows.  I am afraid we can't help you, but here are some ideas:

- If it is your work laptop, contact the helpdesk of your employer.
- If it is your personal machine, try resources provided by Microsoft at  https://support.microsoft.com/en-us/hub/4338813/windows-help
