### ISSUE TITLE
Simplify the IPFS learning curve

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#16]
## Background

@gozala (2017-02-01)
> As you look into IPFS there are just too many things thrown at you that makes bootstrapping unnecessarily complicated.

@gozala (2017-02-07)
> I think the biggest problem from my perspective is that it feels like stack of many low lever technologies and it is not clear what they help me accomplish. From what I gathered that ipfs gives you very flexible and generic toolchain to build more product like things like Dat or OpenBazzaar. I think starting from the product perspective would really help, so you can understand that it can be used to solve this problem, then introducing a product from the other end of the spectrum showing how same IPFS toolchain can be applied to it & there for giving a perspective of a range of applications.
> [...]
>  I think having an examples of specific applications would really help IPFS.

**Comment by flyingzumwalt** [comment]
This work probably won't fit in the [current Sprint](ipfs/pm#351), but should definitely be covered in the [Delightful Documentation](https://github.com/ipfs/pm/issues/357) Sprint later this quarter.

**Comment by lgierth** [comment]
Nothing concretely actionable here
