### ISSUE TITLE
Tool that converts CIDv0 to CIDv1

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#17]
This relates to the discussion of origin domains in #6

**Comment by flyingzumwalt** [comment]
If you're trying to get a CIDv0 and the node has a CIDv1 the node will not be happy.

**Comment by whyrusleeping** [comment]
The issue is that right now, requesting a protobuf object with cidv1 doesnt fetch an object from disk that was stored as a cidv0. I can add in a translation layer that checks cidV0 when certain formats of cidV1s are encountered.

**Comment by lgierth** [comment]
Has there been progress on this?

**Comment by lidel** [comment]
Both  js-ipfs >= [v0.33.0](https://github.com/ipfs/js-ipfs/blob/master/CHANGELOG.md#0330-2018-11-01) and go-ipfs >= [v0.4.18](https://github.com/ipfs/go-ipfs/blob/master/CHANGELOG.md#0418-2018-10-26)  support `ipfs cid` subcommand :


```shell
# cidv0(b58) → cidv1(b32)
$ ipfs cid base32 QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR
bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi

# cidv1(b58) → cidv1(b32)
$ ipfs cid base32 zb2rhk6GMPQF3hfzwXTaNYFLKomMeC6UXdUt6jZKPpeVirLtV
bafkreigh2akiscaildcqabsyg3dfr6chu3fgpregiymsck7e7aqa4s52zy
```

There is also a standalone [js-cid-tool](https://github.com/ipfs-shipyard/js-cid-tool) for converting, formatting and discovering properties of CIDs.
