### ISSUE TITLE
go-ipfs resolves base 16 and base 32 CIDs

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#18]
go-ipfs needs to be able to resolve base 16 and base 32 CIDs. Currently go-ipfs only supports b58.

This is related to the discussion of origin domains in #6

**Comment by Kubuxu** [comment]
Should be possible in 0.4.6, dependency update is already queued up: https://github.com/ipfs/go-ipfs/pull/3649

**Comment by diasdavid** [comment]
👌🏽

**Comment by whyrusleeping** [comment]
This now works in 0.4.6-dev (master)
