### ISSUE TITLE
go-ipfs retrieves content from js-ipfs

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#19]
## Acceptance Criteria

- [ ] a go-ipfs node can consistently & reliably retrieve content from js-ipfs nodes

This requires getting a stream multiplexer functional in both languages.

## Background

go-ipfs and js-ipfs do not share a working stream multiplexer. The ones that work go-go are not implemented in javascript and the ones that work js-js are not implemented in go.

**Comment by whyrusleeping** [comment]
Updates here. After adding in support to go-multiplex for half closed streams (which are, in my opinion, unnecessary) we have discovered that the js implementation of multiplex also does not support half closed streams.

We're working on fixing that

**Comment by diasdavid** [comment]
As soon as these last test passes -- https://github.com/diasdavid/multiplex/pull/2 --, we should be golden!

**Comment by diasdavid** [comment]
@whyrusleeping did you get the chance to bubble up the changes yesterday?

**Comment by whyrusleeping** [comment]
https://github.com/ipfs/go-ipfs/pull/3695 

working on it. Tests arent passing for some reason, will look at them as soon as i can. In the meantime you should be able to build off of that branch and test

**Comment by diasdavid** [comment]
Getting a:

```
» ipfs swarm connect /ip4/127.0.0.1/tcp/14002/ipfs/QmWxqpnDn1ZFcaJQ8nEpAkcTz9xR8foaNXnwpY9THi34e7
Error: connect QmWxqpnDn1ZFcaJQ8nEpAkcTz9xR8foaNXnwpY9THi34e7 failure: dial attempt failed: failed to add conn to ps.Swarm: selected protocol we don't have a transport for
```

**Comment by Kubuxu** [comment]
@diasdavid you have to pass: `--enable-mplex-experiment` to daemon

**Comment by diasdavid** [comment]
It's working \o/ 

![image](https://cloud.githubusercontent.com/assets/1211152/23016807/c866c0b8-f42f-11e6-9601-d8bfa8c4feff.png)

**Comment by diasdavid** [comment]
Continue testing, it works for a lot of cases, but when we start talking about bigfiles (50MB++), go-ipfs kills the connection it has with js-ipfs, doing swarm connect again will result in go-ipfs closing the socket again. This might be related with the tests @whyrusleeping saw failing

**Comment by whyrusleeping** [comment]
@diasdavid is that still the case?

**Comment by dignifiedquire** [comment]
@diasdavid @whyrusleeping what's the status of this? @diasdavid how can I reproduce the panic you are seeing?

**Comment by dignifiedquire** [comment]
Tried the latest branches mentioned here with the interop tests from js-ipfs. Seems there is still a lot of things not working currently. 

Current setup:
- js-ipfs: 78ac8cf13ce76fd53a47a2d76325419a840f38d7 (current `master`)
- go-ipfs: https://github.com/ipfs/go-ipfs/pull/3695

Command:

```
> LIBP2P_MUX_PREFS="/mplex/6.7.0" IPFS_EXEC=`which ipfs` LIBP2P_MUXER=multiplex npm run test:interop:node
```

- go -> js is very slow
- js -> go starts failing for everything `> 1024bit`

**Comment by dignifiedquire** [comment]
I discovered that identify is failing, when using the above mentioned setup, it works fine if I switch to spdy.

**Comment by dignifiedquire** [comment]
More updates

- @whyrusleeping thinks the issues are related to half closing
- I can confirm this, going back to the version go-multiplex@0.2.6 (no support for half close) makes things much better.
- In the interop tests I can observer (with half closing)
  - first test js -> go works
  - every other after fails
  - It seems this is related to streams not being properly closed and/or not being properly reused. 
  - Testing against spdy these issues are not there, so they are specific to muliplex

**Comment by dignifiedquire** [comment]
I have a branch with types + logging for multiplex on the js side here: https://github.com/dignifiedquire/multiplex

**Comment by dignifiedquire** [comment]
@whyrusleeping 

> <•dignifiedquire>  whyrusleeping: good news I figured out why things are broken, due to a bug , the js side is sending multiplex ids starting with 1 again because connection reuse doesn't do what it should be doing
> <•dignifiedquire> but because of halfOpen, the original connection no1 is not closed, so go ipfs gets confused, and things start failing
New messages
<•dignifiedquire> whyrusleeping: so I don't think you need to do anything, will need to go and fix the js side first

**Comment by dignifiedquire** [comment]
Not fully done yet

Still needs

- [ ] https://github.com/ipfs/js-libp2p-ipfs-browser/pull/160
- [ ] https://github.com/ipfs/js-libp2p-ipfs-nodejs/pull/78
- [ ] Interop tests for browser & go-ipfs with multiplex

**Comment by dignifiedquire** [comment]
One more PR: https://github.com/libp2p/js-libp2p-swarm/pull/179 and we are good to go for browser multiplexing!

**Comment by lgierth** [comment]
I think this is done cc @dignifiedquire

**Comment by diasdavid** [comment]
Shipped and released :)
