### ISSUE TITLE
Polish WebRTC signalling server

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#20]
@diasdavid could you clarify what's needed here? What is the end-goal?

**Comment by diasdavid** [comment]
I believe there is nothing to there, this was delivered during the first sprint.

**Comment by lgierth** [comment]
Whether and how we do these is debatable, but these are the remaining webrtc-related tasks I'm aware of.

- [ ] Decide on proper domain name for the webrtc-star signalling server. Right now it's on a preliminary domain name called star-signal.cloud.ipfs.team.
- [ ] js-libp2p-webrtc-star exposing metrics for Prometheus on a separate http port.
- [ ] Enough documentation and clarification on /libp2p-webtrc-star to write a prespec.

It's not properly finished as long as these three tasks are open.
