### ISSUE TITLE
This site can't provide a secure connection

### ISSUE THREAD

**Issue by wuhaiyzq** [ipfs/in-web-browsers#210]
When I visit this website(https://bafybeigyzm5ar4ccgss7bkuafzmkmcxs6h4wtt2pk55bomabaqhusbe2du.ipfs.nftstorage.link/cucutx7qbmwqjfbyws.jpg), I am prompted with an error of 'This site can't provide a secure
connection An SSL error has occurred and a secure cannection to the serwer cannot be made  NSURLErrorSecureConnectlonFalled'
thanks!

**Comment by lidel** [comment]
@wuhaiyzq nftstorage service is not related to this repo, please fill issue in https://github.com/nftstorage/nftstorage.link/issues/new/choose
