### ISSUE TITLE
Figure out what does IPFS in browser brings to the table

### ISSUE THREAD

**Issue by Gozala** [ipfs/in-web-browsers#22]
This maybe too generic of an issue to have it around, but I though I'd create one in any case. As to what I'm proposing - IMO there needs to be a particular, well defined feature that IPFS in browser provides that would gain a user traction. For example Opera shipped [p2p file sharing, chat & static site server](https://www.wired.com/2009/10/opera_unite_puts_the_web_server_in_your_web_browser/) back in 2009 and so did [AllPeers Firefox extension](https://en.wikipedia.org/wiki/AllPeers) in 2006 but neither end up being successful, it's either due to lack of that particular feature or maybe they were just ahead of time. Either way I think it's something worth taking time to consider.

**Comment by flyingzumwalt** [comment]
I'm merging this with #14: Document compelling use cases for IPFS in Browsers
