### ISSUE TITLE
Publish dweb: URI spec draft and documentation

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#28]
Publish URI spec draft and documentation for `fs:` or `dweb:` protocol

Prerequisites: #3, #4, #6

**Comment by flyingzumwalt** [comment]
@jbenet @nicola is it going to be possible to work on this, or any of its prerequisites, this week?

**Comment by lgierth** [comment]
I have the skeleton of a draft here: https://github.com/ipfs/specs/tree/doc/fs-paths/fs-paths

Should I just make that a PR so we can discuss inline?

(Sorry for my super-slow last week.)

**Comment by nicola** [comment]
I wanted to propose something silly, just to make sure we can also take it into consideration:

- rename (or create a symbolic link) `/ipfs` to `/ipfs:`
- so that we can justify `ipfs://hash`, without loosing the original juan's idea, assuming the `dweb`

However, while I am writing this, it is aesthetically really ugly!

**Comment by flyingzumwalt** [comment]
@lgierth please do make a PR.

Also - how can we decide whether to stick with fs: vs dweb: ? I think dweb is more accurate/appropriate, and it also seems to be getting more traction (I hear people mention it more than fs:)

**Comment by lgierth** [comment]
> Also - how can we decide whether to stick with fs: vs dweb: ? I think dweb is more accurate/appropriate, and it also seems to be getting more traction (I hear people mention it more than fs:)

I haven't heard dweb: anywhere before this sprint :) I don't have a strong opinion what it should be, dweb: is certainly less generic than fs:, and has less historical baggage.

This is likely a matter of gathering feedback from externals and friends, who are interested in the future of the project but have less of an internal perspective.

**Comment by lgierth** [comment]
> dweb: is certainly less generic than fs:, and has less historical baggage.

... and sounds less like ipFS, this potentially being more inviting to others.

**Comment by nicola** [comment]
Also, when it is about "data", `fs` might not be the best name!
`fs/dweb` is basically the scheme for the content addressable web (and actually a bit more)

**Comment by lgierth** [comment]
If we're all confident with dweb: that's cool :) @jbenet @diasdavid what do you think?

**Comment by pawal** [comment]
I have offered a full spec on ipfs: and ipns: - short and easy to implement for everybody. Where is the spec on dweb?

https://github.com/ipfs/specs/pull/139

**Comment by lgierth** [comment]
@pawal let's get the IANA registration for ipfs:// and ipns:// rolling based on https://github.com/ipfs/specs/pull/152#issuecomment-284628862

**Comment by pawal** [comment]
@lgierth Not entirely sure what changes are needed based on the background material. Perhaps change the word multihash to hash?
