### ISSUE TITLE
Register URI with IANA

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#29]
Some sort of URI/URL registered with IANA

**Update:** see https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md

**Comment by diasdavid** [comment]
I'm currently working on the IPFS integration for the brave browser and I wasn't sure what to go for when it comes for protocol handler. Which should I use to register a handler:

- `ipfs:/..`
- `ipfs://..`
- `/ipfs/..`
- `dweb:/`
- `dweb://`
- `/dweb/`

??

**Comment by flyingzumwalt** [comment]
related: https://github.com/ipfs/specs/pull/152#issuecomment-284628862

cc @lgierth

**Comment by lgierth** [comment]
Go with `ipfs://` and `ipns://`. If you can, also go with `dweb:` but I doubt that'd work -- from what I understand Brave is based on Electron and its protocol APIs don't support pure URIs yet (is that correct?).

**Comment by lgierth** [comment]
By the way, it's a good time to get URI support into Electron's protocol APIs now. It is because it's also a good time to make a proposal for good progammable protocol handlers in Firefox, and Electron's API might make for a good proposal.

**Comment by ebkalderon** [comment]
Just a curious lurker here. Has anyone arrived at a conclusion about the browser-compatible address scheme to use? Is anyone still monitoring #152?

**Comment by lidel** [comment]
Just for the record, memo about currently suggested URI addressing schemes can be found at:
https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md

**Comment by lidel** [comment]
@jonnycrunch what would be the first step in registering `ipfs://`? 
Should we register `ipns://` together, or is it better to tackle them one by one?

**Comment by lidel** [comment]
IPFS URI Scheme (`ipfs://`) application for IANA is being prepared at [ipfs-uri-scheme](https://github.com/jonnycrunch/ipfs-uri-scheme).

To get up to speed, see [this summary on pre-existing specs, adoption and behaviors](https://github.com/jonnycrunch/ipfs-uri-scheme/issues/1),
where I suggest registration of URN as well.

cc @yiannisbot @jaycarpenter

**Comment by fred-wang** [comment]
Registering to IANA was suggested in order to add ipfs/ipns/dweb to the safelist of registerProtocolHandler(). See https://github.com/whatwg/html/pull/5482#issuecomment-618973427

**Comment by fred-wang** [comment]
Just for the record, I prepared a draft. This is discussed there: https://github.com/jonnycrunch/ipfs-uri-scheme/issues/2#issuecomment-627895142

**Comment by fred-wang** [comment]
Application sent yesterday and accepted.

ipfs/ipns are now listed here: https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

**Comment by lidel** [comment]
Thank you @fred-wang! 

Closing this one as done, tracking URN in https://github.com/ipfs/in-web-browsers/issues/161
