### ISSUE TITLE
Complete IPFS Core API from both js-ipfs and go-ipfs

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#31]
This is from the original sprint notes. @diasdavid @whyrusleeping can you clarify? Might have already been addressed in sprint ipfs/pm#310

**Comment by diasdavid** [comment]
It is essentially about this: https://github.com/ipfs/interface-ipfs-core

Tasks:

- [ ] Spec out remaining core API https://github.com/ipfs/interface-ipfs-core/tree/master/API
  - [ ] https://github.com/ipfs/interface-ipfs-core/pull/38
  - [ ] https://github.com/ipfs/interface-ipfs-core/pull/37
  - [ ] + all the others
- [ ] Make go use them https://github.com/ipfs/interface-ipfs-core/issues/66

**Comment by lidel** [comment]
I believe this can be closed.
Core API lives in https://github.com/ipfs/js-ipfs/tree/master/docs/core-api and go-ipfs can be used as CoreAPI lib (https://github.com/ipfs-inactive/interface-js-ipfs-core/issues/66#issuecomment-549970356)
