### ISSUE TITLE
Dial with websockets from browser to go-ipfs

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#34]

**Comment by whyrusleeping** [comment]
Why is this not already possible? What is the context here? @lgierth @diasdavid  ?

**Comment by lgierth** [comment]
It's just not properly deployed and documented. Some code somewhere down in go-libp2p isn't easy-to-use ;)

**Comment by lgierth** [comment]
What's needed here:

- [ ] fix libp2p/go-ws-transport#8
- [ ] fix libp2p/go-ws-transport#11
- [ ] sharness tests in go-ipfs
- [ ] a bit of documentation
- [ ] mounted in gateway: `/dns4/ipfs.io/tcp/443/ws/ipfs/QmSoL`

**Comment by lgierth** [comment]
And I think there's additional things to sort on the js-ipfs side.

**Comment by jackkleeman** [comment]
Is there an example of this in use? I have code that is working when run from node (even when I import the browser libp2p code directly), but not in the browser , trying to connect to a websocket go peer. Looking at the websocket, a handshake of some kind is happening, starting /multistream/1.0.0, /secio/1.0.0, with data moving in both directions, but the dialByPeerInfo call never completes; no error is returned, it just hangs, and I never even get to the line where I can pull in a stream. On node, it worked perfectly. Is there something I am missing re getting the handshake to succeed in browser?

**Comment by diasdavid** [comment]
This works now :)  \o/ Is there any bugs missing?

When is is 0.4.7 going to be released with multiplex by default? That will be stellar 🌟

**Comment by Kubuxu** [comment]
If everything goes ok, next Wednesday. RC will be this Friday.

**Comment by diasdavid** [comment]
As an update to every follower of this issue:

- You should be able today to use go-ipfs 0.4.7 and js-ipfs master together without any issues.
- We well be releasing js-ipfs 0.23 soon, which contains all the latest fixes and more. Track the release here: https://github.com/ipfs/js-ipfs/issues/795
