### ISSUE TITLE
Pick time for standup calls

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#36]
We've got the hard combination of time zones on this sprint: both Berlin and US Pacific Time. What time can we use for standup calls? They are usually less than 15 minutes and should not ever be more than 30 minutes, so we only need to block out a 30 minute opening each day.

The obvious times:
- 16:30-17:00 UTC
- 18:00-18:30  UTC

Any preferences? Ideas?

**Comment by flyingzumwalt** [comment]
Note: Even though @VictorBjelkholm and @dignifiedquire won't be taking assignments this week, they will need to join the standup calls so they will be up to speed when they start taking work next week.

**Comment by diasdavid** [comment]
I'll be only able to attend the standup Wednesday and Thursday. Flying Tuesday and Friday.

**Comment by dignifiedquire** [comment]
I can't do either of these times. Currently for me doable is either before 16:== UTC or after 20:30 UTC

**Comment by lgierth** [comment]
I can do either of the times proposed here, except for probably one day a week, but given the number of people involved here that's negligible imho.

**Comment by haadcode** [comment]
I can do 16:30-17:00 UTC on Wed and Thu this week, or 18:00-18:30 UTC on Thu. Generally prefer the earlier time.

**Comment by flyingzumwalt** [comment]
Let's do 16:30 today (in 30 minutes) if people are able to swing that. Then we can nail down a consistent time for the rest of the sprint.

@dignifiedquire if we settle on a time that doesn't work for you this week we will record this week's calls and then find a new time slot next week.

**Comment by dignifiedquire** [comment]
sounds good @flyingzumwalt

**Comment by flyingzumwalt** [comment]
Sorry I forgot to record today's call. It was just me, @lgierth and @whyrusleeping. The waffle board shows what they're working on. We just focused on the ["improving dependencies" issues](https://waffle.io/ipfs/in-web-browsers?label=improving%20dependencies). Concluded that those issues will probably take at least the full sprint to handle, especially since we will have to handle websockets and routing.

**Comment by flyingzumwalt** [comment]
Can we do this?
* 17UTC on Tues, Wed and Friday 
* 18UTC on the days when we have a standing conflict (Monday, Thursday) 

Caveats: 
* we might skip this Thursday's standup.
* @dignifiedquire can't do these times, so we will have to adjust next week.
