### ISSUE TITLE
Gospel of IPFS (Dossier for Browser Devs, etc)

### ISSUE THREAD

**Issue by 20zinnm** [ipfs/in-web-browsers#38]
I've begun work on the _Gospel of IPFS_, basically a dossier going over what IPFS is, why it's needed, and how it solves problems. I'll issue occasional RFCs but it'd be great to have the team review it every now and then.

https://github.com/20zinnm/gospel-of-ipfs

**Comment by lgierth** [comment]
Awesome -- let us know if there's anything specific you'd like reviewed.
