### ISSUE TITLE
Web Extension allows choice of daemon: go-ipfs or js-ipfs

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#40]
depends on #11 

Allow a choice of daemon: go-ipfs or js-ipfs -- default to go-ipfs because js-ipfs doesn't support dht lookup yet

**Comment by lgierth** [comment]
Closing this as js-ipfs DHT is being worked on right now and the waffle board needs a cleanup :)

**Comment by lidel** [comment]
Just for sake of discoverability, this was delivered in https://github.com/ipfs/ipfs-companion/pull/320
