### ISSUE TITLE
WebExtension makes **go-ipfs** full ipfs core api (interface-core-api) available in the browser

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#41]
depends on #11

Web extension makes **go-ipfs** protocol (interface-core-api) available in the browser through window.ipfs
  * uses js-ipfs-api to talk with the node
  * using the core api vs relying on the gateway should be disabled/enabled by toggling a "Redirect-URLs" option true or false
  * disable by default

**Comment by haadcode** [comment]
Started looking into this with the idea that js-ipfs-api is packaged with the extension and exposed to window.ipfs.

- Including it in the extension is trivial, just npm install ipfs-api and add the dist build to the manifest.json's background.scripts field 
- We currently build js-ipfs-api to attach to window.IpfsApi. This should be easy to fix/workaround.
- The next step is where I hit a blocker: try to talk to the go-ipfs node via js-ipfs-api is blocked by Content Security Policy.
  - https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_security_policy
  - https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_Security_Policy
  - ***"The only permitted schemes for sources are: blob:, filesystem:, moz-extension:, and https:."*** and ***"Firefox does not support: "http://127.0.0.1" or "http://localhost" as script sources: they must be served over HTTPS."***

What I take from this is that we can't make js-ipfs-api work from the webextension using http://localhost:5001 to communicate with the go-ipfs node like we normally do. Please correct me if I'm wrong.

Next: I'll try other ways to include it.

**Comment by VictorBjelkholm** [comment]
@haadcode I think @whyrusleeping started with using what we discussed in the last call, Native Messaging via stdin/stdout. We would have a layer in between the daemon and the extension that would pass json of some sort via stdin/stdout. https://github.com/whyrusleeping/ipfs-webext

**Comment by haadcode** [comment]
We might be able to apply the same structure here to expose js-ipfs-api as @VictorBjelkholm did in https://github.com/ipfs/in-web-browsers/issues/42#issuecomment-281382909. We'd need that layer in-between, perhaps we could even replace the fetch request in js-ipfs-api with the stdin/out request.

**Comment by flyingzumwalt** [comment]
@haadcode @VictorBjelkholm have we made any progress on this? will we be able to close it out tomorrow and demo on Monday?

**Comment by lidel** [comment]
Delivered in https://github.com/ipfs-shipyard/ipfs-companion/issues/330 :+1:
