### ISSUE TITLE
Demo: Load 3D Object in Universal Viewer over IPFS

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#47]
This is based on work by @edsilv

A potentially exciting demo: load this 3D object over IPFS: http://universalviewer.io/examples/?manifest=https%3A%2F%2Fipfs.io%2Fipfs%2FQmPXKbC96wb6zuUhd8m2HDoovZUqi3gFHbbL9W8vAEQX8a%2For_7694_1595.json#?c=0&m=0&s=0&cv=0

The bad news: If I load this with the browser extension turned on, the only thing telling me that it’s loading over IPFS instead of http is that it takes 10x longer to load :disappointed:

Need to 
* [ ] make it load faster
* [ ] make sure it can work without an internet connection if you've already pinned the tiles (so _all_ of the resources on the page need to be referenced via IPFS links
* [ ] provide some way to show that the content is being resolved over IPFS instead of HTTP

**Comment by whyrusleeping** [comment]
I think step 0 here is to get that viewer page into ipfs so that *it* can be used directly from ipfs

**Comment by whyrusleeping** [comment]
Once we get that, it could go somewhere like `viewer.ipfs.io` or something

**Comment by flyingzumwalt** [comment]
@edsilv @aeschylus can you load the current versions of UV and Mirador into IPFS and let us know the hashes (post in this issue)? Then we can add the dns entries to mirador.ipfs.io and universalviewer.ipfs.io

**Comment by edsilv** [comment]
Hi,

Here's the UV and content entirely in IPFS:

https://ipfs.io/ipfs/QmeP32YQ78D49zC78bmThEjVgrNu4YbHZWNhd4EWbYzttR

Select manifests from the drop down list underneath the UV and click Set to
load other examples.

**Comment by edsilv** [comment]
Fixed a bug with full screen 3D. Also, now using ipns so the url won't change:

https://ipfs.io/ipns/QmfQN7B7WCWo8iRFduptJT5BdEqYzWmXbHKJYzawnmkQBH

**Comment by lgierth** [comment]
Awesome work :)
