### ISSUE TITLE
How do I serve to a gateway

### ISSUE THREAD

**Issue by konsumer** [ipfs/in-web-browsers#49]
I've got a browser-based demo [here](https://codepen.io/konsumer/pen/xqNBJX?editors=0010) that correctly generates a new file and stores it in IndexDB via ipfs-js.

How do I make it's content available on a gateway? I [tried](https://codepen.io/konsumer/pen/ryEwMO?editors=0010) using `bootstrap.add` on hosts from the [the node config](https://github.com/ipfs/js-ipfs/blob/master/src/init-files/default-config-node.json) but that didn't seem to work (or throw an error.)

**Comment by diasdavid** [comment]
@konsumer you have to add the Bootstrap nodes when you create the instance:

```
const ipfs = new Ipfs({
  config: {
    Bootstrap: [
      "/dns4/ams-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
      "/dns4/sfo-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx",
      "/dns4/lon-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3",
      "/dns4/sfo-2.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z",
      "/dns4/sfo-3.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
      "/dns4/sgp-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
      "/dns4/nyc-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
      "/dns4/nyc-2.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64"
    ]
  }
})
```

Let me know if it works for you :) 

This will be added by default once https://github.com/ipfs/js-ipfs/pull/740 is merged.

**Comment by konsumer** [comment]
That totally [worked](https://codepen.io/konsumer/pen/xqNBJX?editors=0010)! Thanks so much!

**Comment by diasdavid** [comment]
Closing this one. Keep us posted of future developments :)

**Comment by JohnAllen** [comment]
This example no longer works, even when removing the 502-returning bootstrap servers. Any thoughts as to why this isn't working?  This is a pretty big bottleneck for us right now with what we're working on -- any help would be greatly appreciated!

**Comment by diasdavid** [comment]
@JohnAllen could you share the issue you are having? I just loaded it and it worked:

![image](https://user-images.githubusercontent.com/1211152/29810832-aafa1132-8ca1-11e7-9ff3-def7084c5e0d.png)

**Comment by konsumer** [comment]
I think it doesn't actually get posted to ipfs. See [this issue](https://github.com/ipfs/js-ipfs/issues/967)

**Comment by lgierth** [comment]
Please file issues with js-ipfs or go-ipfs in the respective repos. This repo is for tracking the work on integrating IPFS into web browsers.

**Comment by diasdavid** [comment]
@lgierth he did, that was the issue linked on the comment above https://github.com/ipfs/js-ipfs/issues/967 ;)

**Comment by lgierth** [comment]
Oh got it -- sorry

**Comment by JohnAllen** [comment]
Will stay in the other, more-to-the-point, [issue](https://github.com/ipfs/js-ipfs/issues/967). (but yeah example works just doesn't pin and isn't available on gateway)

**Comment by buzz** [comment]
Hey, I'm trying the example. The gateway is not able to fetch from the browser.

Tracked your progress through https://github.com/ipfs/js-ipfs/issues/967 and https://github.com/ipfs/js-ipfs/issues/973.

My fork is here: https://codepen.io/anon/pen/LrzBLa?editors=0010

Am I missing something?
