### ISSUE TITLE
IPFS runs as a Service Worker!

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#55]
Run an IPFS node inside a service worker and serve all your IPFS Urls directly from IPFS!

Repo:
https://github.com/ipfs/ipfs-service-worker

Please use this issue to discuss roadmap, etc around this worker. Code discussions go in the repo.

@diasdavid will add a link to a video with demo and discussion from the 22 May All Hands call

**Comment by diasdavid** [comment]
All right, after 14 failed attempts on trimming and uploading the video using 3 different apps, I finally managed to go around Zoom's corrupted files and upload the cut from the All Hands with this demo, woof!

https://youtu.be/xnX0Mz4mPQI

Apologies for the wait

**Comment by dryajov** [comment]
@diasdavid Super stoked on seeing this finally working!!! 👍

**Comment by linonetwo** [comment]
I was inspired and wrote https://github.com/linonetwo/ipfs-browser-gateway
It's very easy to use ipfs in browser now.

**Comment by diasdavid** [comment]
@linonetwo that's rad! Wanna deploy it somewhere so that it is easy to share it with others?

**Comment by linonetwo** [comment]
@diasdavid OK~ I'll deploy it to now.sh after I remove all hardcoded parts

**Comment by lidel** [comment]
@vasco-santos pushed this endeavor further in [ipfs-shipyard/service-worker-gateway](https://github.com/ipfs-shipyard/service-worker-gateway):
> An IPFS gateway fully running on a Service Worker, in order to serve all your IPFS urls directly!

**Comment by lidel** [comment]
- Foreign Fetch for Service Workers got removed from the spec: https://github.com/w3c/ServiceWorker/issues/1188
- Notes on dealing with lack of Foreign Fetch: https://github.com/arewedistributedyet/arewedistributedyet/issues/32  
  - Extracted potential iframe-based workaround: https://github.com/ipfs-shipyard/service-worker-gateway/issues/30

**Comment by Gozala** [comment]
just posting this link here https://github.com/ipfs/in-web-browsers/issues/137 for the relevancy

**Comment by lidel** [comment]
I believe end-to-end example of using js-ipfs node in SharedWorker from ServiceWorker added in https://github.com/ipfs/js-ipfs/pull/3374 is the best we can do on the web platform for now. 

See: https://github.com/ipfs/js-ipfs/tree/master/examples/browser-service-worker#using-js-ipfs-node-in-sharedworker-from-serviceworker
