### ISSUE TITLE
Provide a list of things that we want/need changed in the Web Extension Spec

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#56]
related to #35 

Given our experience building these web extensions, provide a list of things we want or need changed in the Web Extension spec in order to support IPFS in web browsers more cleanly. We will pass this list to the team who are working on the spec.

Example: Allow Web Extensions to provide protocol handlers.

**Comment by lidel** [comment]
Things identified during development of firefox add-on rewrite to WebExtension:
* Support PRogrammable, Custom Protocols with control over how Origin is calculated
  (details at https://github.com/ipfs/ipfs-companion/issues/164, https://github.com/ipfs/in-web-browsers/issues/6#issuecomment-294304978)

    > **tl;dr**: There is an open ticket at Bugzilla about need for better API for _persistent_/programmable protocol handler:
     >   *  [Firefox Bug 1271553 - Add ability to implement programmable custom protocol handler](https://bugzilla.mozilla.org/show_bug.cgi?id=1271553)
     >   * I described the need for ability to control how Origin is handled by custom protocol in Firefox WebExtension:  https://bugzilla.mozilla.org/show_bug.cgi?id=1271553#c47

* Prevent mixed content warnings for TLS sites embedding IPFS resources (https://github.com/ipfs/ipfs-companion/issues/75)
* API for reading TXT DNS records to check if any contains `dnslink` (https://github.com/ipfs/notes/issues/92#issuecomment-287632925)

**Comment by flyingzumwalt** [comment]
**need web workers to support webrtc**

**Comment by dignifiedquire** [comment]
**need fast optimized webrtc data channels**

**Comment by diasdavid** [comment]
- [**need WebCrypto in non secure origins too**](https://github.com/libp2p/js-libp2p-crypto/issues/105)
- **need Streaming option for WebCrypto** [1](https://github.com/libp2p/js-libp2p-crypto/issues/30) [2](https://github.com/w3c/webcrypto/issues/73)
- **need WebRTC in WebWorkers, ServiceWorkers and WebExtensions** [1](https://lists.w3.org/Archives/Public/public-webrtc/2015Oct/0000.html) [2](https://github.com/w3c/webrtc-pc/issues/230) [3](https://bugzilla.mozilla.org/show_bug.cgi?id=922363) [4](https://bugs.chromium.org/p/chromium/issues/detail?id=302019) [5](https://groups.google.com/forum/#!topic/discuss-webrtc/ulHSVgHnnrk) [6](https://github.com/w3c/webrtc-pc/pull/317)
- [**need another way other than the `Origin-Trial` token to signal that we accept a request to be captured by a Service Worker**](https://github.com/ipfs/ipfs-service-worker/issues/5)

**Comment by diasdavid** [comment]
@lgierth @flyingzumwalt what's the follow up to this thread?

**Comment by lgierth** [comment]
We should make this into a comprehensive, prioritized list that we can point browser people too. Ideally with a brief description which features each of the items unlocks. There are things which are absolute dealbreakers (e.g. proper protocol handlers), and things which are important but not essential. The list should convey this importance and priorities.

**Comment by lgierth** [comment]
We can then also use this list to track the outreach and progress for each of the items.

**Comment by lidel** [comment]
FYSA discussion moved to:
- https://github.com/ipfs-shipyard/arewedistributedyet/issues
- https://github.com/mozilla/libdweb/issues
  - https://github.com/ipfs-shipyard/ipfs-companion/issues/343
