### ISSUE TITLE
SWASH Proposal

### ISSUE THREAD

**Issue by samholmes** [ipfs/in-web-browsers#58]
I'd like to share a proposal for a new kind of web address notation that can be used within the IPFS community. The goal is to have a clear definition for a more capable web address notation. Extra capabilities include support for case-sensitive encodings specifically for use with content addresses. The intention of this issue is to garner discussion around the proposal and it's application within the distributed web as a movement.

[The SWASH Proposal Draft](https://github.com/samholmes/swash)

 It is my belief that SWASH benefits the movement by decoupling legacy standards from newer protocol standards. My hope is to settle confusion on adoption paths and distinguishing between the definitions for existing items in the space (supposed existence of a thing called NURI, Nestible URI).

I'll be working on implementation internally for the purpose of investigating the performance of the SWASH proposal at the web browser interface implementation level within the experimental project called [Swiss](https://github.com/samholmes/swiss). Updates on my discoveries will be shared here.

**Comment by RangerMauve** [comment]
Why do IPFS people not want to use URIs?

**Comment by samholmes** [comment]
I don't think I can speak for everyone in the community, and my suggestion for an alternative to URLs is just that, a suggestion.

However, I would argue a reason why I would like to see an new kind of address for the distributed web is because of the challenges that are faced with adopting URLs. For one, URLs are location based and origin+domain is a tightly coupled thing with the current web. The distributed web could use a address scheme that supports case-sensitive _content-addresses_ without any enforced origin coupling.

That is the general thinking behind this proposal, however it might be over-kill.

**Comment by RangerMauve** [comment]
The domain in a URI isn't mandatory, nothing is stopping you from having `ipfs:///hashhere`

**Comment by RangerMauve** [comment]
From what I understand, this is the reason that the beaker browser doesn't have IPFS integration at the moment. dat uses URIs just fine and they don't have domain names either.

**Comment by RangerMauve** [comment]
Sorry if I'm sounding hostile, I'm just not clued in since the proposal doesn't explain why it's necessary. Is there maybe a thread you could link to so that people could read prior discussions as to why people decided to ditch URIs and use a different format?

**Comment by lidel** [comment]
Hello! I hope this helps a bit:

AFAIK the main discussion and some high-level background on Address Schemes can be found at https://github.com/ipfs/specs/pull/152. 

For current consensus, skip to ["Four stages of the upgrade path for path addressing"](https://github.com/ipfs/specs/pull/152#issuecomment-284628862)

(Discussion around schemes is quite fragmented, so try to keep it within mentioned issue)

**Comment by RangerMauve** [comment]
@lidel That's exactly what I needed to see, thank you.

**Comment by lidel** [comment]
As the closing note, your key need:

> The goal is to have a clear definition for a more capable web address notation 

will addressed by spec at  https://github.com/ipfs/specs/tree/master/dweb-addressing (currently work-in-progress).

The discussion continues in https://github.com/ipfs/specs/pull/152#issuecomment-344629083  (lets keep it there, in one place)
