### ISSUE TITLE
Sketch 2018 Plan/Proposal for in-web-browsers Efforts

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#63]
Let's put our heads together to sketch a plan for 2018 efforts around IPFS in web browsers (especially focusing on Q1 and Q2).  We should aim to have a general proposal together by mid-January so we can figure out how to incorporate that proposal into overall IPFS + libp2p planning for Q1 and beyond. 

To get the ball rolling, let's schedule a phone call. There's a short list of people who we need to have on this first call in order to have our technical bases covered: 
- @diasdavid 
- @flyingzumwalt
- @lgierth 
- @kyledrake 
- @lidel

**Comment by diasdavid** [comment]
Let's include @olizilla and @alanshaw as well.

@lidel has shared his candidate KRs from his perspective at https://github.com/ipfs/in-web-browsers/pull/62

**Comment by VictorBjelkholm** [comment]
I'd like to attend this as well.

**Comment by dryajov** [comment]
same here, I'd like to be on the call.

**Comment by flyingzumwalt** [comment]
Let's try using [WhenIsGood](http://whenisgood.net/9m4nqcd) to pick a time. I've set it up with the times that I'm available December 13-31. Please "paint" your availability on the openings that also work for you and submit it with your name. http://whenisgood.net/9m4nqcd

**Comment by diasdavid** [comment]
I've added my availability.

**Comment by diasdavid** [comment]
Also, I gave the README and docs a refresh, go check it out https://github.com/ipfs/in-web-browsers :)

**Comment by diasdavid** [comment]
Adding to this planning call for the quarter, what do you say of us having a weekly check-in call?

**Comment by olizilla** [comment]
I'd like that 👍

**Comment by flyingzumwalt** [comment]
Weekly check in is a big time commitment. Let’s put it on the agenda for this call.

Based on people’s responses there is no time that works for everyone. The time slot with the least conflicts is [16:00 GMT on the 29th](http://whenisgood.net/ResultsPopup?event=9m4nqcd&code=4a7sfjq&slot=1514563200000) Which works for everyone but @kyledrake and @olizilla.

Shall we do that time?

**Comment by olizilla** [comment]
All good. I'll probably be able to do that time.

**Comment by diasdavid** [comment]
SGTM 👍

**Comment by flyingzumwalt** [comment]
I sent out a calendar invitation. I don't have emails for @olizilla and @alanshaw -- @diasdavid could you forward the invite to them?

**Comment by lidel** [comment]
@diasdavid  forward to me as well

**Comment by diasdavid** [comment]
Invited everyone :) 
<img width="302" alt="image" src="https://user-images.githubusercontent.com/1211152/34387786-0903699c-eb28-11e7-8d58-1fb20eba9491.png">

**Comment by lidel** [comment]
Hi all, in case someone missed last meeting's notes, next step here is:
- submit PRs with OKR proposals (PR against [OKR.md](https://github.com/ipfs/in-web-browsers/blob/master/OKR.md) in this repo)
  - everyone declare what they want to work on  or would like to see happen (pitch your own goal)
  - I added some OKRs related to browser extension as a starting point, but its only a piece of the puzzle – please think  about entire "In Web Browser" endevour.

**Comment by diasdavid** [comment]
@kyledrake @lgierth @olizilla @alanshaw @flyingzumwalt please add your proposed OKR to https://github.com/ipfs/in-web-browsers/blob/master/OKR.md ASAP. Thanks!

**Comment by lidel** [comment]
@diasdavid are we supposed to merge PRs as they go, or do we want to keep them open until next meeting?

**Comment by diasdavid** [comment]
@lidel I think for this time both strategies work but given that we already merged some, it will be better to have them all merged so that we are all looking at the same document in the next meeting.

**Comment by lidel** [comment]
Closing note: PR #77 produced an updated [`ROADMAP.md`](https://github.com/ipfs/in-web-browsers/blob/master/ROADMAP.md)

(to keep issues on topic, we will create a new one when its time for Q2 OKRs)
