### ISSUE TITLE
IPFS Integration in the Brave Browser

### ISSUE THREAD

**Issue by daviddias** [ipfs/in-web-browsers#64]
Track progress at: <del>https://github.com/brave/browser-laptop/issues/9556#issuecomment-352453877</del> https://github.com/brave/brave-browser/issues/819

Just leaving this year for discoverability. Locking the convo on this thread, please follow up on the main one ^

**Comment by lidel** [comment]
I'm happy to announce that Brave v1.19 shipped with support for `ipfs://` URI and ability to run local node.

Blogs:
- https://brave.com/brave-integrates-ipfs/
- https://brave.com/ipfs-support/

Press:
- https://www.coindesk.com/brave-browser-native-ipfs-integration-decentralized-web
- https://www.theverge.com/2021/1/19/22238334/brave-browser-ipfs-peer-to-peer-decentralized-transfer-protocol-http-nodes
- https://www.theregister.com/2021/01/19/brave_decentralized_browser/ (given their usual snark, pretty positive :upside_down_face:)

This is just the beginning. Ongoing/future work:

- https://github.com/brave/brave-browser/issues?q=is%3Aopen+is%3Aissue+label%3Afeature%2Fipfs
- https://github.com/brave/brave-browser/projects/32
