### ISSUE TITLE
Define Q2 2018 OKRs for Web Browsers & GUI WG Efforts

### ISSUE THREAD

**Issue by lidel** [ipfs/in-web-browsers#78]
Creating issue to get the ball rolling :8ball: :dash: 

I feel Q1 was a very important exercise in team building and now we have [much better] idea how to formulate meaningful OKRs. 

I propose OKRs for Q2 to be our first topic during weekly sync on Monday (2018-03-26). We should have a draft by the end of that call, or shortly after. Let's collaborate in realtime using [this hackpad](https://hackmd.io/BbDiZTcyQ0-5c7323YB7XA) just to see if it will work better than a PR in GitHub. 

Until Monday, it would be fantastic if everyone took a moment to:
- read Matt's notes and guidance on Q2 OKRs at https://github.com/ipfs/pm/issues/582
- think what is the status of your OKRs for Q1  
- take some notes
  - what should be your OKRs in Q2
  - are our objectives the same, or do we want to reformulate them?
  - what KRs are an ongoing effort and need to be copied from Q1?
  - what to add?
  - feel free to work directly in [this hackpad](https://hackmd.io/BbDiZTcyQ0-5c7323YB7XA)

cc @akrych @hacdias @alanshaw @olizilla @kyledrake

**Comment by lidel** [comment]
> **30 March:** All WGs have their Q2 OKRs ready to freeze

This means we should finish OKRs and move them to spreadsheet by this Friday.

**Comment by lidel** [comment]
:steam_locomotive: :train: :train:  [the draft is here](https://hackmd.io/BbDiZTcyQ0-5c7323YB7XA).
Feel free to provide feedback in this issue or `[directly in document, like this]` :)

**Comment by akrych** [comment]
> Check the slide deck with highlights of the IPFS GUI work (WebUI & Companion) in Q2 2018
(sources by @olizilla ✨ )

Wow - Looks great! <3

**Comment by lidel** [comment]
Next: Q3 planning @ https://github.com/ipfs/in-web-browsers/issues/85
