### ISSUE TITLE
Define Q3 2018 OKRs for In Web Browsers & GUI Efforts

### ISSUE THREAD

**Issue by lidel** [ipfs/in-web-browsers#85]
OKRs for Q3 (https://github.com/ipfs/pm/issues/654) will be on the agenda of our weekly IRC sync (`#ipfs-in-web-browsers` @ freenode) on Monday (2018-07-01).   Let's brainstorm using hackpad (it worked quite well in Q2).
We should have a draft list with viable ideas by the end of that sync, or a week after.

Before Monday sync, it would be fantastic if we find a moment to:
  - how are we going to handle splitting GUI/UX work into separate WG?
     - eg. do we brainstorm together and then split OKRs between two sheets
  - think what excites you: got a pet browser-related OKRs for Q3?
  - are our objectives the same, or do we want to reformulate them?
  - what KRs are an ongoing effort and need to be copied from Q2?
  - what to add?
  - feel free to work directly in <del>[this hackpad](https://hackmd.io/63Ot04yETI6_Lmpa8sjw5A#)</del> (see https://github.com/ipfs/in-web-browsers/issues/85#issuecomment-402707819)

**Comment by lidel** [comment]
For anyone interested, we will be having a joint OKR brainstorming session for GUI & Web Browsers WG on 2018-07-02 @ 4PM UTC.  Link to Zoom call will be posted on `#ipfs-in-web-browsers` @ freenode.

**Comment by lidel** [comment]
Initial OKR Draft moved to separate Sheets of `IPFS 2018 Q3 OKRs`:
- `wb` – [Web Browsers OKRs](https://docs.google.com/spreadsheets/d/19vjigg4locq4fO6JXyobS2yTx-k-fSzlFM5ngZDPDbQ/edit?ts=5b28e2d5#gid=755202447)
- `gui` – [GUI OKRs](https://docs.google.com/spreadsheets/d/19vjigg4locq4fO6JXyobS2yTx-k-fSzlFM5ngZDPDbQ/edit?ts=5b28e2d5#gid=1841105909)

@kyledrake @olizilla @alanshaw @fsdiogo @hacdias

Please take a look at it and comment  in `wb` and `gui` Sheets (or here):
- Do you feel some priorities should be adjusted? Why?
- Are there any KRs you would like to be an Owner or help with? 
  or maybe you would like to add own KR? What is missing?
- Which KRs are too specific and should be merged or reworded?

**Comment by hacdias** [comment]
@lidel don't have permissions to edit the spreadsheet 😢

**Comment by lidel** [comment]
@hacdias are you able to comment there?  If so, add comment describing change you want and `+lidel` me.

If commenting does not work, add your comments here or as an agenda items to our next sync (https://github.com/ipfs/in-web-browsers/issues/88)

**Comment by hacdias** [comment]
@lidel done! I added to the hackpad. Just to let you know, I won't be able to go to the sync up on Monday 😞
