### ISSUE TITLE
Specify APIs for interaction between browser & IPFS

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#9]
@lgierth
> another important thing to deliver (crosscutting the user stories) is a list of concrete features and APIs that we need to make this better

## Background

@gozala:
> What else ? How should these APIs look like ? What restrictions should browser pose in regards to these APIs ? Quotas like indexedDB ? Disallow reads across origins (across hashes ?) ? Should there be a form of CORS for IPFS content ?

@gozala:
> I expect this to be a question with in first top 10 you’d be asked by browser vendors as long as you aim or “dweb apps”. if IPFS is a more positioned as distribution network of  static files than that becomes less relevant. 

In a separate conversation thread: 
@jbenet
> - For now, They can use js-ipfs to have a full ipfs node directly in the browser, or js-ipfs-api to use those APIs. 

@gozala
> That sort of means "dweb apps" get unlimited power to read / write content, which I doubt is going to fly.

@jbenet
> - We want to come up with a nice set of APIs to be provided by {addon, extension, webextensions} that js-ipfs and js-ipfs-api can cleanly polyfill, so adoption can just improve over time.
> - Native APIs are the long-term goal.

@gozala
> I expect browser vendors to be more interested what APIs need to be exposed to allow “dweb apps”, implementation details are less important.

**Comment by lidel** [comment]
If it helps, this is a short list if "things" that are used in [ipfs-firefox-addon](https://github.com/lidel/ipfs-firefox-addon/):

- checking if URL is IPFS resource (is-ipfs) 
- checking if IPFS resource is pinned (js-ipfs-api – `ipfs.pin.ls|add|rm`)
- fetching node metadata (js-ipfs-api) There is a potential room for improvement: right now addon downloads full peer list, as we are lacking API that returns simple 'peer count'.
- uploading file/URL to IPFS (js-ipfs-api: `ipfs.util.addFromURL(url, callback)`)
- (experimental, slow and disabled by default) checking if FQDN has dnslink in in its DNS record (manual request to `/api/v0/dns/` -- js-ipfs-api does not support it, see details in  https://github.com/ipfs/js-ipfs-api/issues/501)

**Comment by lidel** [comment]
Update: there is a proposal for adding DNS-related API to WebExtension API. I've added suggestion to include querying for TXT records (so that [dnslink](https://github.com/ipfs/examples/blob/62650e30ccf6eed19c1e11e3ec5a76d0573b1516/examples/websites/README.md) can be detected natively by the browser):
- https://bugzilla.mozilla.org/show_bug.cgi?id=1343849#c2

**Comment by lgierth** [comment]
Continued in #35
